name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Build and test
      run: xcodebuild clean build test -workspace RestaurantMenu.xcworkspace -scheme "RestaurantMenu" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64 CODE_SIGNING_REQUIRED=NO 
      
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
